tool: sklearn.KMeans
algorithm: elkan
seed: 42
max_iter: 300
tol: 0.0001
K: 800
n_jobs_env: 4
vec_path: embeddings/trained/mk_skipgram.vec
n_words: 84072
dim: 300
runtime_sec: 46.243608236312866
normalized_inputs: true
normalized_centroids: true
