tool: sklearn.KMeans
algorithm: elkan
seed: 42
max_iter: 300
tol: 0.0001
K: 1200
n_jobs_env: 4
vec_path: embeddings/trained/mk_skipgram.vec
n_words: 84072
dim: 300
runtime_sec: 58.70687818527222
normalized_inputs: true
normalized_centroids: true
